/*
 * JobPlannerEnums.h
 *
 *  Created on: 10.06.2011
 *      Author: root
 */

#ifndef JOBPLANNERENUMS_H_
#define JOBPLANNERENUMS_H_

/* Job enums*/

namespace JobClass
{
	enum JobClass {Process=0, Deliver, Recycle, Explore};
	static const char * cJobClass[4] = {"Process", "Deliver", "Recycle", "Explore"};
}

namespace JobType
{
	enum JobType {P1_TO_DEL=0, P2_TO_DEL, P3_TO_DEL, S2_TO_T3, S2_TO_T4, S1_TO_T3, S1_TO_T4, S0_TO_T3, S0_TO_T4, S0_TO_T5, S1_TO_T2, S0_TO_T2, S0_TO_T1, RECYCLE_PUCK_AT_T4_LEFT_PUCK, RECYCLE_PUCK_AT_T4_RIGHT_PUCK, RECYCLE_PUCK_AT_T3_LEFT_PUCK, RECYCLE_PUCK_AT_T3_RIGHT_PUCK, RECYCLE_PUCK_AT_T2_LEFT_PUCK, RECYCLE_PUCK_AT_T2_RIGHT_PUCK, Explore, LO_TO_DEL};
	static const char * cJobType[21] = {"P1_TO_DEL", "P2_TO_DEL", "P3_TO_DEL", "S2_TO_T3", "S2_TO_T4", "S1_TO_T3", "S1_TO_T4", "S0_TO_T3", "S0_TO_T4", "S0_TO_T5", "S1_TO_T2", "S0_TO_T2", "S0_TO_T1", "RECYCLE_PUCK_AT_T4_LEFT_PUCK", "RECYCLE_PUCK_AT_T4_RIGHT_PUCK", "RECYCLE_PUCK_AT_T3_LEFT_PUCK", "RECYCLE_PUCK_AT_T3_RIGHT_PUCK", "RECYCLE_PUCK_AT_T2_LEFT_PUCK", "RECYCLE_PUCK_AT_T2_RIGHT_PUCK", "Explore" , "LO_TO_DEL"};
}

namespace JobProgressStatus
{
	enum JobProgressStatus {DRIVEN_TO_TARGET_MACHINE_1=0, DONE_AT_MACHINE_1, OUT_OF_MACHINE_1, DRIVEN_TO_TARGET_MACHINE_2, DONE_AT_MACHINE_2, FINISHED_JOB, FINISHED_JOB_OUT_OF_ORDER_DURING_FINAL_PROCESSING, STARTING, STARTED};
	static const char * cJobProgressStatus[9] = {"DRIVEN_TO_TARGET_MACHINE_1", "DONE_AT_MACHINE_1", "OUT_OF_MACHINE_1", "DRIVEN_TO_TARGET_MACHINE_2", "DONE_AT_MACHINE_2", "FINISHED_JOB", "FINISHED_JOB_OUT_OF_ORDER_DURING_FINAL_PROCESSING", "STARTING", "STARTED"};
}

#endif /* JOBPLANNERENUMS_H_ */
